### ISSUE TITLE
Gatsby on firebase

### ISSUE THREAD

**Issue by saturnite** [f0rr0/f0rr0.github.io#2]
How did you deploy gatsby on firebase?

**Comment by f0rr0** [comment]
@saturnite Gatsby is not deployed to firebase at all. Firebase is being used as a realtime database with synced updates. https://github.com/tylermcginnis/re-base is the client library I'm using.

**Comment by f0rr0** [comment]
The entire Firebase related logic can be found here https://github.com/f0rr0/f0rr0.github.io/blob/3c897f3b9e78b5333073cbe1fed26565c05832d3/src/components/QuantifiedSelf.jsx

**Comment by saturnite** [comment]
Thank you
